
import React from 'react';
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";

const DisclaimerSection = () => {
  return (
    <section className="py-16 px-4 md:px-6 bg-cyber-dark/60" id="disclaimer">
      <div className="container mx-auto">
        <h2 className="text-3xl md:text-4xl font-cyber font-bold text-center mb-8 neon-text">
          Legal Disclaimer
        </h2>
        
        <Alert className="max-w-4xl mx-auto glass-panel mb-6 border-cyber-secondary/30">
          <AlertTitle className="text-cyber-primary">Usage Information</AlertTitle>
          <AlertDescription>
            <p className="text-white/80">
              <span className="font-bold text-cyber-secondary">FREE ACCESS:</span> Unrestricted usage is free with a ChatGPT Plus account or higher.
              Free accounts have limited interactions every few hours.
            </p>
          </AlertDescription>
        </Alert>
        
        <div className="max-w-4xl mx-auto glass-panel p-8">
          <div className="space-y-6 text-gray-300">
            <p className="font-semibold text-cyber-secondary">IMPORTANT: PLEASE READ THESE TERMS CAREFULLY BEFORE USING THIS SERVICE</p>
            
            <p>
              Children's Picture Book Maker GPT is provided "as is" and "as available" without any warranties, 
              expressed or implied. AI WEB TOOLS LLC does not guarantee the accuracy, completeness, or usefulness 
              of any content generated by the AI.
            </p>
            
            <p>
              By using Children's Picture Book Maker GPT, you acknowledge that:
            </p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>The service utilizes artificial intelligence to generate content and illustrations that may vary in quality and relevance.</li>
              <li>AI WEB TOOLS LLC is not responsible for the content generated by the service, including any potential errors, inaccuracies, or inappropriate content.</li>
              <li>All generated content may be subject to copyright and intellectual property laws, and users are solely responsible for ensuring their use of generated content complies with all applicable laws.</li>
              <li>Images and text created using this service may not be used for commercial purposes without proper verification of rights and compliance with relevant laws.</li>
              <li>AI WEB TOOLS LLC reserves the right to modify, suspend, or discontinue the service at any time without notice.</li>
            </ul>
            
            <p>
              IN NO EVENT SHALL AI WEB TOOLS LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF 
              OR IN ANY WAY CONNECTED WITH THE USE OF CHILDREN'S PICTURE BOOK MAKER GPT.
            </p>
            
            <p>
              This service is not intended to replace professional writing or illustration services. Users are encouraged to review and 
              verify all generated content before publication or distribution.
            </p>
            
            <p>
              By using this service, you agree to indemnify and hold harmless AI WEB TOOLS LLC and its affiliates from any claims, damages, 
              or expenses arising from your use of the service.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
